# Beautify Soup - Enron Events from web

In [18]:
# import libraries
import urllib.request as urllib2
from bs4 import BeautifulSoup
import pandas as pd

In [19]:
# specify the url
quote_page = "https://www.nytimes.com/2006/01/18/business/worldbusiness/timeline-a-chronology-of-enron-corp.html"

In [20]:
# query the website and return the html to the variable ‘page’
page = urllib2.urlopen(quote_page)

In [21]:
# parse the html using beautiful soup and store in variable `soup`
soup = BeautifulSoup(page, "html.parser")

In [22]:
# extract the raw html content from the web
enron_timeline_story_body = soup.find(class_="story-body")

In [23]:
# extract the enron events chronology in list
enron_timeline_raw = enron_timeline_story_body.find_all("p")

In [24]:
# start from the third element which is the first event for enron corp, get the raw text description
enron_event_desc_content_list = [event_html.get_text() for event_html in enron_timeline_raw[2:]]

In [25]:
# identify the four year digit
def isFourYearDigit(str):
    str = str.replace(':', '')

    return len(str) < 5 and str[0:4].isdigit()

In [26]:
# method to return the list of time when event happens and another corresponding list of event descriptions
def get_event_timeline(events):
    date_list = []
    desc_list = []
    year = None

    for event in events:

        event_with_date = event.split("-")
        date = None
        desc = None
    
        if len(event_with_date) == 1 and isFourYearDigit(event_with_date[0]):
            year = event_with_date[0]
            continue;
        
        if len(event_with_date) == 1:
            print(event_with_date)
            date = date_list[-1]
            desc = event_with_date[0]
            continue;
        
        if year:
            date = year + ' ' + event_with_date[0]
        else:
            date = event_with_date[0]
        desc = event_with_date[1]
        
        date_list.append(date)
        desc_list.append(desc)

    return date_list, desc_list

In [27]:
date_list, desc_list = get_event_timeline(enron_event_desc_content_list)

['Each invested $5,800 in 2001 and received a $1 million return a few weeks later.']

In [28]:
enron_events = pd.DataFrame({
            "date": date_list,
            "desc": desc_list,
         })

In [29]:
enron_events

               date                                               desc
0             1985    Houston Natural Gas merges with InterNorth to...
1             1989       Enron begins trading natural gas commodities.
2             1990    Lay hires Jeffrey Skilling to lead the compan...
3             1991    Richard Causey leaves Arthur Andersen LLP to ...
4             1997    Skilling named president and chief operating ...
5             1998                         Fastow named finance chief.
6              1999   Causey named chief accounting officer. Fastow...
7      August 2000                     Enron shares reach high of $90.
8    December 2000    Enron announces that Skilling, then president...
9    2001: Aug. 14              Skilling resigns; Lay named CEO again.
10   2001: Aug. 22    Finance executive Sherron Watkins meets priva...
11   2001: Oct. 16               Enron announces $638 million in third
12   2001: Oct. 19    Securities and Exchange Commission launches i...
13   2001: Oct. 22    Enron acknowledges SEC inquiry into a possibl...
14   2001: Oct. 23     Lay professes confidence in Fastow to analysts.
15   2001: Oct. 24                                      Fastow ousted.
16    2001: Nov. 5               Enron treasurer Ben Glisan Jr. and in
17    2001: Nov. 8    Enron files documents with SEC revising its f...
18    2001: Nov. 9    Dynegy Inc. announces an agreement to buy Enr...
19   2001: Nov. 19                            Enron restates its third
20   2001: Nov. 28    Enron stock plunges below $1 as Dynegy Inc. a...
21    2001: Dec. 2    Enron goes bankrupt, thousands of workers lai...
22    2002: Jan. 9    Justice Department confirms it has begun a cr...
23   2002: Jan. 10    The White House discloses Lay sought help fro...
24   2002: Jan. 23                    Lay resigns as chairman and CEO.
25   2002: Jan. 25    Cliff Baxter, former head of Enron's trading ...
26    2002: Feb. 4                         Lay resigns from the board.
27    2002: Feb. 7    Skilling, Fastow, Michael Kopper appear at Co...
28   2002: Feb. 12    Lay invokes Fifth Amendment at a Senate heari...
29  2002: March 14    Former Enron auditor Arthur Andersen LLP indi...
30   2002: April 9    David Duncan, Andersen's former top Enron aud...
31   2002: June 15                                 Andersen convicted.